import type { ClientLogo } from "@/content/types";

export const clientLogos: ClientLogo[] = [
  {
    name: "Grupo Fiero",
    logo: "/clients/grupo-fiero.jpg",
    alt: "Logo de Grupo Fiero",
    featured: false,
    order: 1,
  },
  {
    name: "La Gaditana Taberna",
    logo: "/clients/la-gaditana-taberna.jpg",
    alt: "Logo de La Gaditana Taberna",
    featured: false,
    order: 2,
  },
  {
    name: "La Lonjería",
    logo: "/clients/la-lonjeria.jpg",
    alt: "Logo de La Lonjería",
    featured: false,
    order: 3,
  },
  {
    name: "Sagaretxe",
    logo: "/clients/sagaretxe.jpg",
    alt: "Logo de Restaurante Sagaretxe Catering",
    featured: false,
    order: 4,
  },
  {
    name: "PH",
    logo: "/clients/ph.jpg",
    alt: "Logo de PH",
    featured: false,
    order: 5,
  },
  {
    name: "Ondarreta",
    logo: "/clients/ondarreta.jpg",
    alt: "Logo de Ondarreta",
    featured: false,
    order: 6,
  },
  {
    name: "El Urogallo",
    logo: "/clients/el-urogallo.jpg",
    alt: "Logo de El Urogallo Restaurantes",
    featured: false,
    order: 7,
  },
  {
    name: "Falling Leaves",
    logo: "/clients/falling-leaves.jpg",
    alt: "Logo de Falling Leaves",
    featured: false,
    order: 8,
  },
  {
    name: "El Café de La Ópera",
    logo: "/clients/el-cafe-de-la-opera.jpg",
    alt: "Logo de El Café de La Ópera",
    featured: false,
    order: 9,
  },
  {
    name: "A'Barra Restaurante",
    logo: "/clients/abarra-restaurante.jpg",
    alt: "Logo de A'Barra Restaurante",
    featured: false,
    order: 10,
  },
  {
    name: "Cucurucho",
    logo: "/clients/cucurucho.jpg",
    alt: "Logo de Cucurucho",
    featured: false,
    order: 11,
  },
  {
    name: "Roostiq",
    logo: "/clients/roostiq.jpg",
    alt: "Logo de Roostiq Organic Mood",
    featured: false,
    order: 12,
  },
  {
    name: "Frívolos",
    logo: "/clients/frivolos.jpg",
    alt: "Logo de Frívolos",
    featured: false,
    order: 13,
  },
];
